name: Sync ZH to GH

on:
  push:
    branches:
      - master
  # schedule:
  #   - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  sync:
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      ZH_TOKEN: ${{ secrets.ZH_TOKEN }}
      Z2G_COLUMN_NAMES_MAP: '{"Backlog":["Current Sprint","Upcoming Sprint","Backlog","Current Initiatives/Epics","Icebox"],"In Progress":["Blocked/Has Dependency","Review/QA","In Progress"]}'
      Z2G_LABEL: platform-tech-team-3
      Z2G_ORGANIZATION: department-of-veterans-affairs
      Z2G_PROJECT: 807
      Z2G_REPOSITORY: va.gov-team
      Z2G_WORKSPACE_ID: 6335ab9b1901b99243ce7601

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: ruby z2g.rb
